console.log('[] to Number: ' + Number([]))
console.log('[123] to Number: ' + Number([123]))
console.log('[123，1] to Number: ' + Number([123,1]))
console.log('{} to Number: ' + Number({}))
console.log('{a:1} to Number: ' + Number({a:1}))
console.log(`'' to Number: ${Number('')}`)
console.log(`'123' to Number: ${Number('123')}`)
console.log(`'a' to Number: ${Number('a')}`)
console.log('true to Number: ' + Number(true))
console.log('false to Number: ' + Number(false))
console.log('null to Number: ' + Number(null))
console.log('undefined to Number: ' + Number(undefined))
console.log('--------------------------------------------')
console.log('[] to String: ' + String([]))
console.log('[123,1] to String: ' + String([123,1]))
console.log('{} to String: ' + String({}))
console.log('{a:1} to String: ' + String({a:1}))
console.log(`'' to String: ${String('')}`)
console.log('true to String: ' + String(true))
console.log('false to String: ' + String(false))
console.log('1 to String: ' + String(1))
console.log('0 to String: ' + String(0))
console.log('null to String: ' + String(null))
console.log('undefined to String: ' + String(undefined))
console.log('--------------------------------------------')
console.log('[] to Boolean: ' + Boolean([]))
console.log('[1,2] to Boolean: ' + Boolean([1,2]))
console.log('{} to Boolean: ' + Boolean({}))
console.log('{a:1} to Boolean: ' + Boolean({a:1}))
console.log(`'a' to Boolean: ${Boolean('a')}`)
console.log(`'123' to Boolean: ${Boolean('123')}`)
console.log(`'' to Boolean: ${Boolean('')}`)
console.log('1 to Boolean: ' + Boolean(1))
console.log('0 to Boolean: ' + Boolean(0))
console.log('null to Boolean: ' + Boolean(null))
console.log('undefined to Boolean: ' + Boolean(undefined))
